[package]
edition = "2021"
name = "moodlight"
version = "0.1.0"

[dependencies]
anyhow = "1.0.44"
env_logger = "0.9.0"
envy = "0.4.2"
gethostname = "0.2.1"
log = "0.4.14"
rumqttc = "0.8.0"
serde = {version = "1.0.130", features = ["derive"]}
serde_json = "1.0.68"
tokio = {version = "1.11.0", features = ["macros", "rt", "io-util", "fs"]}
